### ISSUE TITLE
log analyzer is crashing 

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#1293]
Traceback:

```
Found 20 log files
Found 29 manifests
Traceback (most recent call last):
  File "/opus/src/pds-opus/log_analyzer/log_analyzer.py", line 159, in <module>
    main()
  File "/opus/src/pds-opus/log_analyzer/log_analyzer.py", line 110, in main
    configuration = cast(AbstractConfiguration, module.Configuration(**vars(args)))  # type: ignore
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opus/src/pds-opus/log_analyzer/opus/configuration.py", line 37, in __init__
    self._slug_map = slug.ToInfoMap(api_host_url)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opus/src/pds-opus/log_analyzer/opus/slug.py", line 96, in __init__
    raw_json = self.__read_json(url_prefix)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opus/src/pds-opus/log_analyzer/opus/slug.py", line 297, in __read_json
    info = json.loads(text)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Logs and manifests are in DropBox in the -2023-02 directories.

**Comment by rfrenchseti** [comment]
This is actually a bug with fields.json

**Comment by fyellin** [comment]
I am modifying log analyzer to give a better error message if this happens again.  log analyzer should have caught that the URL wasn't returning a status 200.

**Comment by rfrenchseti** [comment]
Reopening so we can associate it with the pull request
