### ISSUE TITLE
Gallery table view fails when no sort order

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-opus#411]
Click on the table headers until there is no sort order. We get:

[Sun Aug 05 10:22:21.817525 2018] [wsgi:error] [pid 23524:tid 140401235764992] Traceback (most recent call last):
[Sun Aug 05 10:22:21.817527 2018] [wsgi:error] [pid 23524:tid 140401235764992]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
[Sun Aug 05 10:22:21.817528 2018] [wsgi:error] [pid 23524:tid 140401235764992]     response = get_response(request)
[Sun Aug 05 10:22:21.817530 2018] [wsgi:error] [pid 23524:tid 140401235764992]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
[Sun Aug 05 10:22:21.817531 2018] [wsgi:error] [pid 23524:tid 140401235764992]     response = self._get_response(request)
[Sun Aug 05 10:22:21.817533 2018] [wsgi:error] [pid 23524:tid 140401235764992]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
[Sun Aug 05 10:22:21.817534 2018] [wsgi:error] [pid 23524:tid 140401235764992]     response = self.process_exception_by_middleware(e, request)
[Sun Aug 05 10:22:21.817535 2018] [wsgi:error] [pid 23524:tid 140401235764992]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
[Sun Aug 05 10:22:21.817537 2018] [wsgi:error] [pid 23524:tid 140401235764992]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Aug 05 10:22:21.817538 2018] [wsgi:error] [pid 23524:tid 140401235764992]   File "/rdsk/www/django/src/pds-opus/opus/application/apps/results/views.py", line 72, in api_get_data
[Sun Aug 05 10:22:21.817540 2018] [wsgi:error] [pid 23524:tid 140401235764992]     ret = get_data(request, fmt)
[Sun Aug 05 10:22:21.817541 2018] [wsgi:error] [pid 23524:tid 140401235764992]   File "/rdsk/www/django/src/pds-opus/opus/application/apps/results/views.py", line 497, in get_data
[Sun Aug 05 10:22:21.817542 2018] [wsgi:error] [pid 23524:tid 140401235764992]     (page_no, limit, page, opus_ids, ring_obs_ids, order) = get_page(request)
[Sun Aug 05 10:22:21.817543 2018] [wsgi:error] [pid 23524:tid 140401235764992]   File "/rdsk/www/django/src/pds-opus/opus/application/apps/results/views.py", line 737, in get_page
[Sun Aug 05 10:22:21.817545 2018] [wsgi:error] [pid 23524:tid 140401235764992]     ('-' if descending else '') + order)
[Sun Aug 05 10:22:21.817546 2018] [wsgi:error] [pid 23524:tid 140401235764992] UnboundLocalError: local variable 'descending' referenced before assignment

**Comment by rfrenchseti** [comment]
This crash has been fixed, but it really shouldn't be possible to have no sort order.

**Comment by rfrenchseti** [comment]
I've fixed this by enforcing an ultimate default sort order - Observations are always sorted by time last, even if they are sorted by other things first. This guarantees a deterministic sort result. So it's really OK to not have a sort order from the UI's point of view.
